package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"example/graph/model"
	"fmt"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.SummedAns, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Sum is the resolver for the sum field.
func (r *queryResolver) Sum(ctx context.Context, arg1 int, arg2 int) (*model.SummedAns, error) {
	res, err := r.calculateSum(ctx, arg1, arg2)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
