// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type SummedAns struct {
	FirstParam  int `json:"firstParam"`
	SecondParam int `json:"secondParam"`
	TotalSum    int `json:"totalSum"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
